[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.22"

[workspace]
types = "packages/validator-bonds-sdk/generated/"

[features]
seeds = true
skip-lint = false

[programs.mainnet]
validator_bonds = "vBoNdEvzMrSai7is21XgVYik65mqtaKXuSdMBJ1xkW4"

[programs.devnet]
validator_bonds = "vBoNdEvzMrSai7is21XgVYik65mqtaKXuSdMBJ1xkW4"

[programs.localnet]
validator_bonds = "vBoNdEvzMrSai7is21XgVYik65mqtaKXuSdMBJ1xkW4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
