agents:
  queue: "snapshots"

steps:
  - command: echo "--> Start of concurrency gate"
    concurrency_group: 'validator-bonds/claim-settlements'
    concurrency: 1

  - wait: ~

  - label: ":hammer_and_wrench: :rust: Build"
    commands:
    - '. "$HOME/.cargo/env"'
    - 'cargo build --release --bin list-claimable-epoch'
    - 'cargo build --release --bin claim-settlement'
    artifact_paths:
      - target/release/list-claimable-epoch
      - target/release/claim-settlement
  
  - wait: ~

  - label: ":campfire: List claimable epochs"
    env:
      # RUST_LOG: trace
      # RUST_BACKTRACE: full
    commands:
    - '. "$HOME/.cargo/env"'
    - 'buildkite-agent artifact download --include-retried-jobs target/release/list-claimable-epoch .'
    - 'chmod +x target/release/list-claimable-epoch'
    - 'claimable_epochs_json=$(./target/release/list-claimable-epoch --rpc-url $$RPC_URL)'
    - 'buildkite-agent meta-data set claimable_epochs_json "$$claimable_epochs_json"'

  - wait: ~

  - label: ":floppy_disk: :arrow_left: :cloud: Downloading all epochs merkle trees"
    env:
      gs_bucket: gs://marinade-validator-bonds-mainnet
    commands:
    - 'mkdir ./merkle-trees/'
    - 'claimable_epochs_json=$(buildkite-agent meta-data get claimable_epochs_json)'
    - 'claimable_epochs_num=$(echo "$$claimable_epochs_json" | jq "length")'
    - 'echo "Claimable epochs [$$claimable_epochs_num]: $$claimable_epochs_json"'
    - 'buildkite-agent meta-data set claimable_epochs_num "$$claimable_epochs_num"'
    - |
      if [ "$$claimable_epochs_num" -eq 0 ]; then
        echo "No claimable epochs found"
        exit 0
      fi
    - |
      for epoch in $(echo "$$claimable_epochs_json" | jq ".[]"); do
        gcloud storage cp "$$gs_bucket/$$epoch/settlement-merkle-trees.json" "./merkle-trees/$${epoch}_settlement-merkle-trees.json"
        gcloud storage cp "$$gs_bucket/$$epoch/settlements.json" "./merkle-trees/$${epoch}_settlements.json"
      done
    artifact_paths:
      - "./merkle-trees/*"

  - wait: ~

  - label: ":campfire: Claim settlements"
    env:
      # RUST_LOG: trace
      # RUST_BACKTRACE: full
    commands:
    - |
      claimable_epochs_num=$(buildkite-agent meta-data get claimable_epochs_num)
      [ "$$claimable_epochs_num" -eq 0 ] && echo 'No settlement to claim from' && exit 0
    - 'buildkite-agent artifact download --include-retried-jobs "merkle-trees/*" .'
    - '. "$HOME/.cargo/env"'
    - 'buildkite-agent artifact download --include-retried-jobs target/release/claim-settlement .'
    - 'chmod +x target/release/claim-settlement'
    - |
      ./target/release/claim-settlement \
        --rpc-url $$RPC_URL \
        --merkle-trees-dir "./merkle-trees/" \
        --operator-authority "$$VALIDATOR_BONDS_OPERATOR_AUTHORITY" \
        --fee-payer "$$VALIDATOR_BONDS_FUNDING_WALLET" \
        --fetch-pause-millis 400

  - wait: ~

  - command: echo "End of concurrency gate <--"
    concurrency_group: 'validator-bonds/claim-settlements'
    concurrency: 1
